version: '3.8'
services:
    profdevdb:
      image: mysql:latest
      ports:
        - 3306:3306
      env_file:
        ./user-auth/.env
      environment:
        MYSQL_ROOT_PASSWORD: 123
    gateway:
      build: ./gateway
      volumes:
        - ./gateway/src:/usr/src/app/src
      ports:
        - 3000:3000
      command: npm run start:dev
      environment:
        - PORT=3000
    users-auth:
      build: ./user-auth
      volumes:
        - ./user-auth/src:/usr/src/app/src
      command: npm run start:dev
    nats:
      image: nats
      ports:
        - "4222:4222"
    